local settings = require("core.settings")

return {
	{ "tpope/vim-fugitive", lazy = true, cmd = { "Git", "G" } },
	{
		"pysan3/fcitx5.nvim",
		lazy = true,
		event = "BufReadPost",
		cond = vim.fn.executable("fcitx5-remote") == 1,
		config = require("tool.fcitx5"),
	},
	{
		"Bekaboo/dropbar.nvim",
		lazy = false,
		config = require("tool.dropbar"),
		dependencies = { "nvim-tree/nvim-web-devicons", "nvim-telescope/telescope-fzf-native.nvim" },
	},
	{
		"nvim-tree/nvim-tree.lua",
		lazy = true,
		cmd = { "NvimTreeToggle", "NvimTreeOpen", "NvimTreeFindFile", "NvimTreeFindFileToggle", "NvimTreeRefresh" },
		config = require("tool.nvim-tree"),
	},
	{ "ibhagwan/smartyank.nvim", lazy = true, event = "BufReadPost", config = require("tool.smartyank") },
	{
		"michaelb/sniprun",
		lazy = true,
		build = "bash ./install.sh",
		cmd = { "SnipRun", "SnipReset", "SnipInfo" },
		config = require("tool.sniprun"),
	},
	{
		"akinsho/toggleterm.nvim",
		lazy = true,
		cmd = {
			"ToggleTerm",
			"ToggleTermSetName",
			"ToggleTermToggleAll",
			"ToggleTermSendVisualLines",
			"ToggleTermSendCurrentLine",
			"ToggleTermSendVisualSelection",
		},
		config = require("tool.toggleterm"),
	},
	{
		"folke/trouble.nvim",
		lazy = true,
		cmd = { "Trouble", "TroubleToggle", "TroubleRefresh" },
		config = require("tool.trouble"),
	},
	{
		"folke/which-key.nvim",
		lazy = true,
		event = { "CursorHold", "CursorHoldI" },
		config = require("tool.which-key"),
	},
	{
		"olimorris/codecompanion.nvim",
		enabled = settings.use_chat,
		lazy = true,
		cmd = {
			"CodeCompanion",
			"CodeCompanionActions",
			"CodeCompanionChat",
			"CodeCompanionCLI",
			"CodeCompanionCmd",
			"CodeCompanionHistory",
			"CodeCompanionSummaries",
		},
		config = require("tool.codecompanion"),
		dependencies = { { "ravitemer/codecompanion-history.nvim" } },
	},
	{
		"ibhagwan/fzf-lua",
		lazy = true,
		cond = settings.search_backend == "fzf",
		cmd = "FzfLua",
		config = require("tool.fzf-lua"),
		dependencies = { "nvim-tree/nvim-web-devicons" },
	},
	{
		"nvim-telescope/telescope.nvim",
		lazy = true,
		cmd = "Telescope",
		config = require("tool.telescope"),
		dependencies = {
			{ "nvim-lua/plenary.nvim" },
			{ "nvim-tree/nvim-web-devicons" },
			{ "jvgrootveld/telescope-zoxide" },
			{ "debugloop/telescope-undo.nvim" },
			{ "nvim-telescope/telescope-frecency.nvim" },
			{ "nvim-telescope/telescope-live-grep-args.nvim" },
			{ "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
			{ "ayamir/search.nvim", config = require("tool.search") },
			{
				"DrKJeff16/project.nvim",
				event = { "CursorHold", "CursorHoldI" },
				config = require("tool.project"),
			},
			{
				"aaronhallaert/advanced-git-search.nvim",
				cmd = { "AdvancedGitSearch" },
				dependencies = { "tpope/vim-rhubarb", "tpope/vim-fugitive", "sindrets/diffview.nvim" },
			},
		},
	},
	{
		"mfussenegger/nvim-dap",
		lazy = true,
		cmd = {
			"DapSetLogLevel",
			"DapShowLog",
			"DapContinue",
			"DapToggleBreakpoint",
			"DapToggleRepl",
			"DapStepOver",
			"DapStepInto",
			"DapStepOut",
			"DapTerminate",
		},
		config = require("tool.dap"),
		dependencies = {
			{ "jay-babu/mason-nvim-dap.nvim" },
			{ "rcarriga/nvim-dap-ui", dependencies = "nvim-neotest/nvim-nio", config = require("tool.dap.dapui") },
		},
	},
}
