return {
	{
		"goolord/alpha-nvim",
		lazy = true,
		event = "BufWinEnter",
		config = require("ui.alpha"),
	},
	{
		"akinsho/bufferline.nvim",
		lazy = true,
		event = { "BufReadPre", "BufAdd", "BufNewFile" },
		config = require("ui.bufferline"),
	},
	{
		"Jint-lzxy/nvim",
		lazy = false,
		branch = "refactor/syntax-highlighting",
		name = "catppuccin",
		config = require("ui.catppuccin"),
	},
	{
		"lewis6991/gitsigns.nvim",
		lazy = true,
		event = { "CursorHold", "CursorHoldI" },
		config = require("ui.gitsigns"),
	},
	{
		"lukas-reineke/indent-blankline.nvim",
		lazy = true,
		event = { "CursorHold", "CursorHoldI" },
		config = require("ui.indent-blankline"),
	},
	{
		"nvim-lualine/lualine.nvim",
		lazy = true,
		event = { "BufReadPost", "BufAdd", "BufNewFile" },
		config = require("ui.lualine"),
	},
	{
		"karb94/neoscroll.nvim",
		lazy = true,
		event = { "CursorHold", "CursorHoldI" },
		config = require("ui.neoscroll"),
	},
	{
		"rcarriga/nvim-notify",
		lazy = true,
		event = "VeryLazy",
		config = require("ui.notify"),
	},
	{
		"folke/paint.nvim",
		lazy = true,
		event = { "CursorHold", "CursorHoldI" },
		config = require("ui.paint"),
	},
	{
		"mrjones2014/smart-splits.nvim",
		lazy = true,
		event = { "CursorHoldI", "CursorHold" },
		config = require("ui.splits"),
	},
	{
		"folke/edgy.nvim",
		lazy = true,
		event = { "CursorHold", "CursorHoldI" },
		config = require("ui.edgy"),
	},
	{
		"folke/todo-comments.nvim",
		lazy = true,
		event = { "CursorHold", "CursorHoldI" },
		config = require("ui.todo"),
		dependencies = "nvim-lua/plenary.nvim",
	},
	{
		"dstein64/nvim-scrollview",
		lazy = true,
		event = { "BufReadPost", "BufAdd", "BufNewFile" },
		config = require("ui.scrollview"),
	},
}
